source "https://rubygems.org"

gem "jekyll", "~> 4.2.0"
gem "jekyll-paginate"
gem "jekyll-feed"
gem "jekyll-sitemap"
gem "jekyll-seo-tag"
gem "jekyll-redirect-from"



group :jekyll_plugins do
  gem "jekyll-archives"
end

platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end